import {
  BadgeCheck,
  BookOpen,
  Flame,
  Gavel,
  Landmark,
  LibraryBig,
  Medal,
  Scale,
  ScrollText,
  ShieldCheck,
  Sparkles,
  Target,
  Timer,
  Trophy,
  Vote,
  Zap,
} from "lucide-react";

export const USER_NAME_KEY = "samvidhanUserName";
export const PROGRESS_KEY = "samvidhanProgress";
export const LEADERBOARD_KEY = "samvidhanLeaderboard";

export const levels = [
  { xp: 0, name: "Citizen" },
  { xp: 100, name: "Beginner" },
  { xp: 250, name: "Intermediate" },
  { xp: 500, name: "Pro" },
  { xp: 800, name: "Constitutional Warrior" },
  { xp: 1200, name: "Constitution Expert" },
  { xp: 2000, name: "Guardian of Democracy" },
];

export const badges = [
  { id: "first_quiz", icon: Trophy, title: "First Quiz", description: "Complete your first quiz." },
  { id: "rights_defender", icon: Scale, title: "Rights Defender", description: "Score well in Fundamental Rights." },
  { id: "article_master", icon: ScrollText, title: "Article Master", description: "Answer article-based questions correctly." },
  { id: "constitutional_warrior", icon: Medal, title: "Constitutional Warrior", description: "Reach 800 XP." },
  { id: "quiz_streak", icon: Flame, title: "5 Quiz Streak", description: "Complete five quizzes in a row." },
  { id: "perfect_score", icon: Target, title: "Perfect Score", description: "Score 100% in any quiz." },
  { id: "speed_master", icon: Zap, title: "Speed Master", description: "Complete Rapid Fire with at least 80%." },
  { id: "knowledge_seeker", icon: BookOpen, title: "Knowledge Seeker", description: "Open Learn Mode." },
];

export const quizModes = [
  { id: "practice", title: "Practice Mode", icon: BookOpen, timer: null, questionCount: 12, description: "Relaxed learning with explanations after every answer." },
  { id: "challenge", title: "Challenge Mode", icon: Timer, timer: 30, questionCount: 12, description: "Beat the 30-second clock on each question." },
  { id: "rapid", title: "Rapid Fire", icon: Zap, timer: 15, questionCount: 10, description: "Fast 10-question sprint for sharp recall." },
  { id: "mock", title: "Mock Test", icon: BadgeCheck, timer: null, questionCount: 50, description: "A 50-question exam-style mixed test." },
];

export const categories = [
  {
    id: "preamble",
    title: "Preamble",
    icon: ScrollText,
    accent: "from-orange-500 to-amber-300",
    description: "Values, ideals, and the identity of the Republic.",
    articles: ["Sovereign", "Socialist", "Secular", "Democratic", "Republic"],
    notes: [
      "The Preamble states the philosophy and objectives of the Constitution.",
      "It declares India to be sovereign, socialist, secular, democratic, and republic.",
      "Justice, liberty, equality, and fraternity guide the constitutional vision.",
    ],
    facts: ["The words Socialist and Secular were added by the 42nd Amendment.", "The Preamble is based on the Objectives Resolution."],
  },
  {
    id: "rights",
    title: "Fundamental Rights",
    icon: Scale,
    accent: "from-blue-500 to-cyan-300",
    description: "Articles 12-35 and everyday civil liberties.",
    articles: ["Article 14", "Article 19", "Article 21", "Article 25", "Article 32"],
    notes: [
      "Fundamental Rights protect individual liberty and equality.",
      "Article 32 allows citizens to approach the Supreme Court directly.",
      "Reasonable restrictions balance freedom with public order and security.",
    ],
    facts: ["Article 21 has expanded through judicial interpretation.", "Right to constitutional remedies was called the heart and soul by Dr. B. R. Ambedkar."],
  },
  {
    id: "duties",
    title: "Fundamental Duties",
    icon: ShieldCheck,
    accent: "from-emerald-500 to-lime-300",
    description: "Article 51A and responsible citizenship.",
    articles: ["Article 51A", "42nd Amendment", "86th Amendment"],
    notes: [
      "Fundamental Duties remind citizens of civic responsibilities.",
      "They include respecting the Constitution, National Flag, and National Anthem.",
      "A duty to provide education to children was added by the 86th Amendment.",
    ],
    facts: ["The duties were inspired by the Constitution of the former USSR.", "There are currently eleven Fundamental Duties."],
  },
  {
    id: "directive",
    title: "Directive Principles",
    icon: LibraryBig,
    accent: "from-violet-500 to-fuchsia-300",
    description: "Part IV and goals for social and economic justice.",
    articles: ["Article 36", "Article 39", "Article 40", "Article 44", "Article 45"],
    notes: [
      "Directive Principles guide the State in making welfare laws.",
      "They are not directly enforceable in courts.",
      "They aim to build social, economic, and political justice.",
    ],
    facts: ["They were inspired by the Irish Constitution.", "Article 40 directs the State to organize village panchayats."],
  },
  {
    id: "parliament",
    title: "Parliament",
    icon: Landmark,
    accent: "from-sky-500 to-blue-300",
    description: "Lok Sabha, Rajya Sabha, bills, and law-making.",
    articles: ["Article 79", "Article 80", "Article 81", "Article 110", "Article 368"],
    notes: [
      "Parliament consists of the President, Lok Sabha, and Rajya Sabha.",
      "Money Bills can be introduced only in Lok Sabha.",
      "Constitutional amendments follow Article 368.",
    ],
    facts: ["Rajya Sabha is a permanent House.", "The Speaker certifies whether a bill is a Money Bill."],
  },
  {
    id: "judiciary",
    title: "Judiciary",
    icon: Gavel,
    accent: "from-indigo-500 to-blue-300",
    description: "Supreme Court, High Courts, writs, and judicial review.",
    articles: ["Article 124", "Article 226", "Article 32", "Article 141"],
    notes: [
      "The Supreme Court is the highest court in India.",
      "High Courts can issue writs under Article 226.",
      "Judicial review helps protect constitutional supremacy.",
    ],
    facts: ["Article 141 makes Supreme Court law binding on all courts.", "Writs include habeas corpus, mandamus, prohibition, quo warranto, and certiorari."],
  },
  {
    id: "amendments",
    title: "Amendments",
    icon: Sparkles,
    accent: "from-rose-500 to-orange-300",
    description: "How the Constitution evolves over time.",
    articles: ["Article 368", "42nd Amendment", "44th Amendment", "73rd Amendment", "74th Amendment"],
    notes: [
      "Article 368 explains the amendment procedure.",
      "Some amendments need a special majority and state ratification.",
      "The basic structure doctrine limits Parliament's amending power.",
    ],
    facts: ["The 42nd Amendment is often called the Mini Constitution.", "The 44th Amendment changed property from a Fundamental Right to a legal right."],
  },
  {
    id: "executive",
    title: "President & Prime Minister",
    icon: Medal,
    accent: "from-amber-500 to-yellow-300",
    description: "Union executive, cabinet, and constitutional roles.",
    articles: ["Article 52", "Article 53", "Article 74", "Article 75", "Article 78"],
    notes: [
      "The President is the constitutional head of the Union.",
      "The Prime Minister leads the Council of Ministers.",
      "The President acts on aid and advice of the Council of Ministers.",
    ],
    facts: ["Article 74 deals with aid and advice.", "The Council of Ministers is collectively responsible to Lok Sabha."],
  },
  {
    id: "elections",
    title: "Elections",
    icon: Vote,
    accent: "from-green-500 to-emerald-300",
    description: "Election Commission, voting, and democratic mandate.",
    articles: ["Article 324", "Article 325", "Article 326"],
    notes: [
      "The Election Commission supervises elections in India.",
      "Adult suffrage is the basis of Lok Sabha and Assembly elections.",
      "Free and fair elections are essential to democracy.",
    ],
    facts: ["Article 324 gives powers to the Election Commission.", "Article 326 deals with adult suffrage."],
  },
  {
    id: "misc",
    title: "Constitution Facts",
    icon: Trophy,
    accent: "from-slate-400 to-white",
    description: "Schedules, parts, symbols, and quick facts.",
    articles: ["Schedules", "Parts", "Citizenship", "Emergency", "Federalism"],
    notes: [
      "The Constitution balances federal and unitary features.",
      "Schedules organize important constitutional details.",
      "Emergency provisions are designed for extraordinary situations.",
    ],
    facts: ["The Constitution came into force on 26 January 1950.", "26 November is observed as Constitution Day."],
  },
];

const q = (category, question, options, answer, explanation, tags = []) => ({
  id: `${category}-${Math.random().toString(36).slice(2)}`,
  category,
  question,
  options,
  answer,
  explanation,
  tags,
});

export const questionBank = [
  q("preamble", "Which word in the Preamble means India is free from external control?", ["Sovereign", "Secular", "Republic", "Fraternity"], "Sovereign", "Sovereign means India has independent authority over internal and external matters."),
  q("preamble", "The Preamble begins with which phrase?", ["We, the People of India", "In the name of Parliament", "By order of the President", "Union of States"], "We, the People of India", "The phrase shows that the Constitution draws authority from the people."),
  q("preamble", "Which amendment added Socialist and Secular to the Preamble?", ["42nd Amendment", "44th Amendment", "73rd Amendment", "86th Amendment"], "42nd Amendment", "The 42nd Amendment, 1976 added Socialist, Secular, and Integrity."),
  q("preamble", "A school debate asks which Preamble ideal means brotherhood among citizens. What is the answer?", ["Fraternity", "Liberty", "Justice", "Republic"], "Fraternity", "Fraternity promotes brotherhood, dignity of the individual, and unity of the nation."),
  q("preamble", "Which Preamble value is most connected with fair treatment before law?", ["Equality", "Liberty", "Secularism", "Sovereignty"], "Equality", "Equality ensures equal status and opportunity for citizens."),
  q("preamble", "India being a Republic means the head of state is:", ["Elected", "Hereditary monarch", "Military ruler", "Foreign nominee"], "Elected", "A republic has an elected head of state, not a hereditary monarch."),
  q("preamble", "The Preamble is based mainly on which historic resolution?", ["Objectives Resolution", "Quit India Resolution", "Lahore Resolution", "Nehru Report"], "Objectives Resolution", "The Objectives Resolution moved by Jawaharlal Nehru shaped the Preamble."),
  q("preamble", "Which term reflects equal respect for all religions by the State?", ["Secular", "Sovereign", "Republic", "Federal"], "Secular", "Secularism means the State does not privilege one religion over others."),
  q("preamble", "Which ideal includes social, economic, and political dimensions?", ["Justice", "Liberty", "Fraternity", "Integrity"], "Justice", "The Preamble promises social, economic, and political justice."),
  q("preamble", "Which Preamble promise protects thought, expression, belief, faith, and worship?", ["Liberty", "Equality", "Justice", "Republic"], "Liberty", "Liberty in the Preamble includes thought, expression, belief, faith, and worship."),
  q("preamble", "The Preamble declares India to be which type of democracy?", ["Democratic Republic", "Direct monarchy", "Military democracy", "Colonial dominion"], "Democratic Republic", "India is a democratic republic where representatives are elected by the people."),
  q("preamble", "Which word added by the 42nd Amendment emphasizes national unity?", ["Integrity", "Federal", "Adult", "Cabinet"], "Integrity", "Integrity was added to strengthen the idea of national unity."),

  q("rights", "Which Article guarantees equality before law?", ["Article 14", "Article 19", "Article 21", "Article 32"], "Article 14", "Article 14 provides equality before law and equal protection of laws.", ["article"]),
  q("rights", "Freedom of speech and expression is protected under:", ["Article 19", "Article 17", "Article 24", "Article 44"], "Article 19", "Article 19 protects several freedoms including speech and expression.", ["article"]),
  q("rights", "Which Article protects life and personal liberty?", ["Article 21", "Article 15", "Article 18", "Article 25"], "Article 21", "Article 21 protects the right to life and personal liberty.", ["article"]),
  q("rights", "A person approaches the Supreme Court directly for violation of Fundamental Rights. Which Article helps?", ["Article 32", "Article 40", "Article 51A", "Article 110"], "Article 32", "Article 32 provides the right to constitutional remedies.", ["article"]),
  q("rights", "Untouchability is abolished by which Article?", ["Article 17", "Article 16", "Article 20", "Article 29"], "Article 17", "Article 17 abolishes untouchability and forbids its practice.", ["article"]),
  q("rights", "A child below 14 is employed in a hazardous factory. Which right is violated?", ["Right against exploitation", "Right to property", "Cultural right", "Right to vote"], "Right against exploitation", "Article 24 prohibits child labour in factories and hazardous employment."),
  q("rights", "Which right protects religious freedom?", ["Right to freedom of religion", "Right against exploitation", "Right to equality", "Right to property"], "Right to freedom of religion", "Articles 25-28 protect freedom of religion."),
  q("rights", "Which writ means 'produce the body'?", ["Habeas corpus", "Mandamus", "Certiorari", "Quo warranto"], "Habeas corpus", "Habeas corpus protects against unlawful detention."),
  q("rights", "Which Article prohibits discrimination on grounds such as religion, race, caste, sex, or place of birth?", ["Article 15", "Article 19", "Article 23", "Article 31"], "Article 15", "Article 15 prohibits certain forms of discrimination.", ["article"]),
  q("rights", "A journalist criticizes a policy peacefully. Which freedom is most relevant?", ["Freedom of speech", "Freedom of trade only", "Freedom from taxes", "Freedom of titles"], "Freedom of speech", "Peaceful criticism is protected by freedom of speech, subject to reasonable restrictions."),
  q("rights", "Which right allows minorities to conserve their language and culture?", ["Cultural and educational rights", "Right to equality", "Right to property", "Right against exploitation"], "Cultural and educational rights", "Articles 29-30 protect cultural and educational rights of minorities."),
  q("rights", "Which Fundamental Right was removed and made a legal right?", ["Right to property", "Right to life", "Right to equality", "Right to education"], "Right to property", "The 44th Amendment removed property from Fundamental Rights and Article 300A protects it as a legal right."),

  q("duties", "Fundamental Duties are mainly listed in which Article?", ["Article 51A", "Article 32", "Article 21", "Article 368"], "Article 51A", "Article 51A lists Fundamental Duties of citizens.", ["article"]),
  q("duties", "Fundamental Duties were added by which amendment?", ["42nd Amendment", "1st Amendment", "44th Amendment", "73rd Amendment"], "42nd Amendment", "The 42nd Amendment added Fundamental Duties in 1976."),
  q("duties", "Which duty asks citizens to respect the National Flag and National Anthem?", ["Respect constitutional symbols", "Pay income tax only", "Vote in every election", "Join public service"], "Respect constitutional symbols", "Article 51A asks citizens to respect the Constitution, Flag, and Anthem."),
  q("duties", "A citizen protects a public bus from vandalism. Which duty is reflected?", ["Safeguard public property", "Defend legal contracts", "Contest elections", "Collect taxes"], "Safeguard public property", "Protecting public property is a Fundamental Duty."),
  q("duties", "Which duty concerns scientific temper?", ["Develop scientific temper and humanism", "Form political parties", "Own private property", "Choose ministers"], "Develop scientific temper and humanism", "Article 51A promotes scientific temper, humanism, inquiry, and reform."),
  q("duties", "The duty to provide education to children aged 6-14 was added by:", ["86th Amendment", "42nd Amendment", "61st Amendment", "101st Amendment"], "86th Amendment", "The 86th Amendment added this duty for parents or guardians."),
  q("duties", "Which country inspired India's Fundamental Duties?", ["Former USSR", "United States", "Canada", "Australia"], "Former USSR", "The duties were inspired by the Constitution of the former USSR."),
  q("duties", "Which duty asks citizens to protect forests, lakes, rivers, and wildlife?", ["Protect environment", "Pay customs duty", "Preserve contracts", "Promote monarchy"], "Protect environment", "Citizens have a duty to protect and improve the natural environment."),
  q("duties", "Respecting ideals of the freedom struggle is a:", ["Fundamental Duty", "Fundamental Right", "Money Bill", "Writ"], "Fundamental Duty", "Article 51A includes cherishing noble ideals of the freedom struggle."),
  q("duties", "Which duty is linked with promoting harmony beyond religious and linguistic differences?", ["Promote brotherhood", "Claim titles", "Avoid education", "Suspend elections"], "Promote brotherhood", "Citizens should promote harmony and common brotherhood."),
  q("duties", "Are Fundamental Duties directly enforceable like Fundamental Rights?", ["No", "Yes, always", "Only by the President", "Only during emergency"], "No", "Duties are generally not directly enforceable, but laws may support them."),
  q("duties", "Striving for excellence in all spheres is mentioned as:", ["A Fundamental Duty", "A Directive Principle only", "A writ", "A cabinet rule"], "A Fundamental Duty", "Citizens should strive toward excellence so the nation rises higher."),

  q("directive", "Directive Principles are found in which Part of the Constitution?", ["Part IV", "Part III", "Part II", "Part X"], "Part IV", "Directive Principles of State Policy are in Part IV."),
  q("directive", "Are Directive Principles directly enforceable in courts?", ["No", "Yes", "Only in High Courts", "Only in Parliament"], "No", "They guide governance but are not directly enforceable by courts."),
  q("directive", "Which Constitution inspired many Directive Principles?", ["Irish Constitution", "French Constitution", "Japanese Constitution", "Brazilian Constitution"], "Irish Constitution", "DPSPs were largely inspired by Ireland."),
  q("directive", "Article 40 directs the State to organize:", ["Village panchayats", "Supreme Court benches", "Military courts", "Stock exchanges"], "Village panchayats", "Article 40 promotes organization of village panchayats."),
  q("directive", "A policy for equal pay for equal work reflects which constitutional area?", ["Directive Principles", "Emergency provisions", "Citizenship", "Schedules"], "Directive Principles", "Article 39 includes equal pay for equal work."),
  q("directive", "Uniform Civil Code is mentioned in:", ["Article 44", "Article 14", "Article 21", "Article 110"], "Article 44", "Article 44 directs the State to endeavour for a Uniform Civil Code.", ["article"]),
  q("directive", "Which principle promotes free legal aid?", ["Article 39A", "Article 17", "Article 52", "Article 324"], "Article 39A", "Article 39A promotes equal justice and free legal aid.", ["article"]),
  q("directive", "Directive Principles aim to establish which kind of democracy beyond politics?", ["Social and economic democracy", "Hereditary democracy", "Military democracy", "Colonial democracy"], "Social and economic democracy", "They promote welfare, equality, and social justice."),
  q("directive", "Which Article promotes protection of environment and wildlife?", ["Article 48A", "Article 19", "Article 80", "Article 111"], "Article 48A", "Article 48A directs the State to protect the environment and wildlife.", ["article"]),
  q("directive", "Separation of judiciary from executive is directed by:", ["Article 50", "Article 32", "Article 72", "Article 300A"], "Article 50", "Article 50 directs separation of judiciary from executive in public services.", ["article"]),
  q("directive", "DPSPs are mainly addressed to:", ["The State", "Private clubs", "Foreign governments", "Only courts"], "The State", "Directive Principles guide the State in law and policy making."),
  q("directive", "Which Directive Principle concerns early childhood care and education?", ["Article 45", "Article 20", "Article 51", "Article 123"], "Article 45", "Article 45 deals with early childhood care and education.", ["article"]),

  q("parliament", "India's Parliament consists of the President and which two Houses?", ["Lok Sabha and Rajya Sabha", "Vidhan Sabha and Council", "Supreme Court and High Court", "Cabinet and Council"], "Lok Sabha and Rajya Sabha", "Article 79 provides for Parliament with the President and two Houses."),
  q("parliament", "Which House is known as the House of the People?", ["Lok Sabha", "Rajya Sabha", "Vidhan Parishad", "Cabinet"], "Lok Sabha", "Lok Sabha directly represents the people."),
  q("parliament", "Which House is permanent and not subject to dissolution?", ["Rajya Sabha", "Lok Sabha", "State Assembly", "Municipality"], "Rajya Sabha", "Rajya Sabha is a continuing House; one-third members retire periodically."),
  q("parliament", "Money Bills can be introduced only in:", ["Lok Sabha", "Rajya Sabha", "Supreme Court", "NITI Aayog"], "Lok Sabha", "Money Bills are introduced only in Lok Sabha."),
  q("parliament", "Who certifies a Money Bill?", ["Speaker of Lok Sabha", "Prime Minister", "Chief Justice", "President of India"], "Speaker of Lok Sabha", "The Speaker's certificate is decisive for Money Bills."),
  q("parliament", "The constitutional amendment procedure is mainly in:", ["Article 368", "Article 14", "Article 51A", "Article 324"], "Article 368", "Article 368 lays down how the Constitution may be amended.", ["article"]),
  q("parliament", "Which list includes subjects such as defence and foreign affairs?", ["Union List", "State List", "Concurrent List", "Village List"], "Union List", "Parliament has exclusive power on Union List subjects."),
  q("parliament", "A bill passed by both Houses usually needs whose assent to become law?", ["President", "Chief Justice", "Governor only", "Comptroller"], "President", "A bill becomes an Act after presidential assent."),
  q("parliament", "Question Hour primarily helps Parliament to:", ["Hold the executive accountable", "Select judges", "Conduct elections", "Write textbooks"], "Hold the executive accountable", "Members ask ministers questions, increasing accountability."),
  q("parliament", "The Council of Ministers is collectively responsible to:", ["Lok Sabha", "Rajya Sabha only", "Supreme Court", "Election Commission"], "Lok Sabha", "Collective responsibility to Lok Sabha is a key parliamentary principle."),
  q("parliament", "Which officer presides over Rajya Sabha?", ["Vice-President of India", "Speaker", "Prime Minister", "Attorney General"], "Vice-President of India", "The Vice-President is the ex-officio Chairman of Rajya Sabha."),
  q("parliament", "A no-confidence motion is moved in:", ["Lok Sabha", "Rajya Sabha", "Supreme Court", "Election Commission"], "Lok Sabha", "The government must retain confidence of Lok Sabha."),

  q("judiciary", "The Supreme Court of India was established under which Article?", ["Article 124", "Article 324", "Article 40", "Article 110"], "Article 124", "Article 124 provides for the establishment and constitution of the Supreme Court.", ["article"]),
  q("judiciary", "High Courts can issue writs under:", ["Article 226", "Article 75", "Article 80", "Article 51A"], "Article 226", "Article 226 gives High Courts writ jurisdiction.", ["article"]),
  q("judiciary", "Judicial review means courts can:", ["Examine constitutionality of laws", "Make budgets", "Conduct elections", "Appoint ministers"], "Examine constitutionality of laws", "Judicial review protects the supremacy of the Constitution."),
  q("judiciary", "Which writ orders a public authority to perform a duty?", ["Mandamus", "Habeas corpus", "Quo warranto", "Prohibition"], "Mandamus", "Mandamus means 'we command' and compels performance of public duty."),
  q("judiciary", "Which Article makes Supreme Court law binding on all courts?", ["Article 141", "Article 44", "Article 17", "Article 300A"], "Article 141", "Article 141 states that law declared by the Supreme Court is binding.", ["article"]),
  q("judiciary", "A detained person is not produced before a magistrate. Which writ may help?", ["Habeas corpus", "Mandamus", "Certiorari", "Quo warranto"], "Habeas corpus", "Habeas corpus protects personal liberty against unlawful detention."),
  q("judiciary", "Which body resolves disputes between the Union and States?", ["Supreme Court", "Election Commission", "Finance Commission", "Lok Sabha Speaker"], "Supreme Court", "The Supreme Court has original jurisdiction in federal disputes."),
  q("judiciary", "Public Interest Litigation mainly helps:", ["Access to justice for public causes", "Private inheritance only", "Tax collection", "Army recruitment"], "Access to justice for public causes", "PIL relaxes standing rules for issues affecting public interest."),
  q("judiciary", "Which is the highest court in a State?", ["High Court", "District Court", "Gram Nyayalaya", "Consumer Forum"], "High Court", "A High Court is the highest constitutional court in a State."),
  q("judiciary", "The independence of judiciary is supported by:", ["Security of tenure of judges", "Daily elections of judges", "Ministerial control", "Private funding only"], "Security of tenure of judges", "Judicial independence needs protected tenure and conditions of service."),
  q("judiciary", "Which writ questions the legal authority of a person holding public office?", ["Quo warranto", "Habeas corpus", "Mandamus", "Certiorari"], "Quo warranto", "Quo warranto asks by what authority a public office is held."),
  q("judiciary", "Which doctrine says Parliament cannot destroy core constitutional principles?", ["Basic structure doctrine", "Pleasure doctrine", "Pith and substance only", "Colorable legislation only"], "Basic structure doctrine", "The basic structure doctrine limits constitutional amendments."),

  q("amendments", "Which Article deals with amendment of the Constitution?", ["Article 368", "Article 32", "Article 14", "Article 51A"], "Article 368", "Article 368 contains the main amendment procedure.", ["article"]),
  q("amendments", "Which amendment is called the Mini Constitution?", ["42nd Amendment", "44th Amendment", "7th Amendment", "101st Amendment"], "42nd Amendment", "The 42nd Amendment made wide-ranging constitutional changes."),
  q("amendments", "Which amendment restored several protections after the Emergency era?", ["44th Amendment", "42nd Amendment", "52nd Amendment", "86th Amendment"], "44th Amendment", "The 44th Amendment reversed or modified several Emergency-era changes."),
  q("amendments", "Panchayati Raj received constitutional status through:", ["73rd Amendment", "74th Amendment", "61st Amendment", "101st Amendment"], "73rd Amendment", "The 73rd Amendment constitutionalized Panchayati Raj institutions."),
  q("amendments", "Municipalities received constitutional status through:", ["74th Amendment", "73rd Amendment", "42nd Amendment", "44th Amendment"], "74th Amendment", "The 74th Amendment constitutionalized urban local bodies."),
  q("amendments", "Voting age was reduced from 21 to 18 by:", ["61st Amendment", "42nd Amendment", "86th Amendment", "97th Amendment"], "61st Amendment", "The 61st Amendment lowered the voting age to 18."),
  q("amendments", "Right to Education was added as a Fundamental Right by:", ["86th Amendment", "44th Amendment", "52nd Amendment", "73rd Amendment"], "86th Amendment", "The 86th Amendment inserted Article 21A.", ["article"]),
  q("amendments", "The anti-defection law was introduced by:", ["52nd Amendment", "42nd Amendment", "44th Amendment", "101st Amendment"], "52nd Amendment", "The 52nd Amendment added the Tenth Schedule."),
  q("amendments", "GST was introduced through which constitutional amendment?", ["101st Amendment", "86th Amendment", "73rd Amendment", "42nd Amendment"], "101st Amendment", "The 101st Amendment enabled Goods and Services Tax."),
  q("amendments", "Which amendment changed Right to Property into a legal right?", ["44th Amendment", "42nd Amendment", "1st Amendment", "7th Amendment"], "44th Amendment", "The 44th Amendment removed Right to Property from Part III."),
  q("amendments", "Which schedule contains anti-defection provisions?", ["Tenth Schedule", "First Schedule", "Seventh Schedule", "Ninth Schedule"], "Tenth Schedule", "The Tenth Schedule deals with disqualification on grounds of defection."),
  q("amendments", "State ratification is needed for amendments affecting:", ["Federal features", "Only school rules", "Only criminal trials", "Only local festivals"], "Federal features", "Changes to federal provisions need ratification by at least half the States."),

  q("executive", "Which Article says there shall be a President of India?", ["Article 52", "Article 124", "Article 324", "Article 40"], "Article 52", "Article 52 creates the office of the President.", ["article"]),
  q("executive", "Executive power of the Union is vested in:", ["President", "Speaker", "Chief Justice", "Comptroller"], "President", "Article 53 vests Union executive power in the President.", ["article"]),
  q("executive", "The President acts on aid and advice of:", ["Council of Ministers", "Election Commission", "Supreme Court registry", "Rajya Sabha only"], "Council of Ministers", "Article 74 provides for aid and advice by the Council of Ministers."),
  q("executive", "Who is the head of the Council of Ministers?", ["Prime Minister", "President", "Vice-President", "Speaker"], "Prime Minister", "The Prime Minister leads the Council of Ministers."),
  q("executive", "The Council of Ministers is collectively responsible to:", ["Lok Sabha", "Supreme Court", "Rajya Sabha only", "President only"], "Lok Sabha", "Article 75 provides collective responsibility to Lok Sabha."),
  q("executive", "Who appoints the Prime Minister?", ["President", "Chief Justice", "Speaker", "Election Commissioner"], "President", "The President appoints the Prime Minister, usually the leader with Lok Sabha majority."),
  q("executive", "Which power lets the President return a non-money bill for reconsideration?", ["Suspensive veto", "Judicial veto", "Budget veto only", "Electoral veto"], "Suspensive veto", "The President may return a non-money bill once for reconsideration."),
  q("executive", "Who is the Supreme Commander of the Defence Forces?", ["President", "Prime Minister", "Speaker", "Chief Election Commissioner"], "President", "The President is the Supreme Commander of India's Defence Forces."),
  q("executive", "Which Article mentions duties of the Prime Minister to furnish information to the President?", ["Article 78", "Article 17", "Article 110", "Article 300A"], "Article 78", "Article 78 defines certain duties of the Prime Minister.", ["article"]),
  q("executive", "The Vice-President is ex-officio Chairman of:", ["Rajya Sabha", "Lok Sabha", "Supreme Court", "Finance Commission"], "Rajya Sabha", "The Vice-President presides over Rajya Sabha as its Chairman."),
  q("executive", "Ordinance-making power of the President is in:", ["Article 123", "Article 32", "Article 51A", "Article 368"], "Article 123", "Article 123 empowers the President to promulgate ordinances when Parliament is not in session.", ["article"]),
  q("executive", "A minister must be a member of Parliament within how many months of appointment?", ["Six months", "One month", "Two years", "Five years"], "Six months", "A non-member minister must become a member within six months."),

  q("elections", "Which Article gives superintendence of elections to the Election Commission?", ["Article 324", "Article 368", "Article 21", "Article 124"], "Article 324", "Article 324 vests election supervision in the Election Commission.", ["article"]),
  q("elections", "Universal adult suffrage means voting rights are based mainly on:", ["Adult citizenship", "Property ownership", "Education level", "Tax paid"], "Adult citizenship", "Adult citizens have the right to vote subject to constitutional and legal limits."),
  q("elections", "Voting age for Lok Sabha elections is:", ["18 years", "21 years", "25 years", "30 years"], "18 years", "The voting age is 18 after the 61st Amendment."),
  q("elections", "Who conducts elections to Parliament and State Legislatures?", ["Election Commission of India", "Supreme Court", "Finance Commission", "Union Cabinet"], "Election Commission of India", "The Election Commission administers these elections."),
  q("elections", "A fair election requires:", ["Secret ballot and equal vote value", "Only rich voters", "No campaign rules", "Hereditary seats"], "Secret ballot and equal vote value", "Free and fair elections depend on secrecy, equality, and independent administration."),
  q("elections", "Which Article prohibits exclusion from electoral rolls on grounds of religion, race, caste, or sex?", ["Article 325", "Article 51A", "Article 123", "Article 75"], "Article 325", "Article 325 bars special electoral rolls based on these grounds.", ["article"]),
  q("elections", "The Model Code of Conduct applies during:", ["Election period", "Court vacations", "Budget printing only", "Census only"], "Election period", "The Model Code guides parties and candidates during elections."),
  q("elections", "EVM stands for:", ["Electronic Voting Machine", "Election Value Manual", "Executive Vote Motion", "Emergency Voter Method"], "Electronic Voting Machine", "EVMs are used to record votes electronically."),
  q("elections", "VVPAT helps voters verify:", ["Their vote was recorded as intended", "Their tax status", "Their school record", "Their court case"], "Their vote was recorded as intended", "VVPAT provides a paper trail for voter verification."),
  q("elections", "Who is responsible for delimitation after Parliament provides by law?", ["Delimitation Commission", "Prime Minister alone", "Local police", "Supreme Court registry"], "Delimitation Commission", "Delimitation redraws constituency boundaries."),
  q("elections", "A candidate bribing voters attacks which democratic principle?", ["Free and fair elections", "Judicial review", "Federal taxation", "Cabinet secrecy"], "Free and fair elections", "Bribery distorts voter choice and election integrity."),
  q("elections", "Election disputes for Parliament are generally decided by:", ["High Courts under election law", "Village panchayat", "Cabinet Secretariat", "Foreign courts"], "High Courts under election law", "Election petitions are handled under election laws, generally by High Courts."),

  q("misc", "When did the Constitution of India come into force?", ["26 January 1950", "15 August 1947", "26 November 1949", "2 October 1950"], "26 January 1950", "The Constitution came into force on 26 January 1950."),
  q("misc", "When was the Constitution adopted by the Constituent Assembly?", ["26 November 1949", "26 January 1950", "15 August 1947", "30 January 1948"], "26 November 1949", "The Constituent Assembly adopted the Constitution on 26 November 1949."),
  q("misc", "Who chaired the Drafting Committee?", ["Dr. B. R. Ambedkar", "Mahatma Gandhi", "Sardar Patel", "Rajendra Prasad"], "Dr. B. R. Ambedkar", "Dr. B. R. Ambedkar chaired the Drafting Committee."),
  q("misc", "India is described in Article 1 as:", ["Union of States", "Federation of Kingdoms", "Confederation of Provinces", "Unitary monarchy"], "Union of States", "Article 1 says India, that is Bharat, shall be a Union of States.", ["article"]),
  q("misc", "Which schedule contains distribution of powers through Union, State, and Concurrent Lists?", ["Seventh Schedule", "First Schedule", "Tenth Schedule", "Twelfth Schedule"], "Seventh Schedule", "The Seventh Schedule contains the three legislative lists."),
  q("misc", "Citizenship provisions are primarily in which Part?", ["Part II", "Part III", "Part IV", "Part IX"], "Part II", "Part II deals with citizenship at the commencement of the Constitution."),
  q("misc", "Emergency due to war, external aggression, or armed rebellion is:", ["National Emergency", "Financial Emergency", "President's Rule", "Local Emergency"], "National Emergency", "Article 352 provides for National Emergency."),
  q("misc", "President's Rule in a State is under:", ["Article 356", "Article 32", "Article 110", "Article 19"], "Article 356", "Article 356 deals with failure of constitutional machinery in States.", ["article"]),
  q("misc", "Financial Emergency is under:", ["Article 360", "Article 44", "Article 74", "Article 17"], "Article 360", "Article 360 provides for Financial Emergency.", ["article"]),
  q("misc", "The Constitution Day of India is observed on:", ["26 November", "15 August", "2 October", "30 January"], "26 November", "26 November marks adoption of the Constitution."),
  q("misc", "Which Schedule contains languages recognized by the Constitution?", ["Eighth Schedule", "Second Schedule", "Ninth Schedule", "Eleventh Schedule"], "Eighth Schedule", "The Eighth Schedule lists recognized languages."),
  q("misc", "Which feature means both Union and States have constitutional powers?", ["Federalism", "Monarchy", "Dictatorship", "Theocracy"], "Federalism", "Federalism divides powers between Union and States under the Constitution."),
].map((item, index) => ({ ...item, id: `${item.category}-${index + 1}` }));

export const seededLeaderboard = [
  { name: "Aarav", score: 920, level: "Constitution Expert", badgeCount: 6 },
  { name: "Priya", score: 760, level: "Constitutional Warrior", badgeCount: 5 },
  { name: "Nikhil", score: 610, level: "Pro", badgeCount: 4 },
  { name: "Meera", score: 480, level: "Intermediate", badgeCount: 3 },
];
